apiVersion: apps/v1
kind: Deployment
metadata:
  name: javaspringboot
spec:
  selector:
    matchLabels:
      app: javaspringboot
  replicas: 1
  template:
    metadata:
      labels:
        app: javaspringboot
    spec:
      containers:
      - name: javaspringboot
        image: gopac/gopac25-javaspringboot:latest
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: production-microservice
---
apiVersion: v1
kind: Service
metadata:
  name: javaspringboot-service

spec:
  selector:
    app: javaspringboot

  ports:
    - name: http
      port: 8080

  type: LoadBalancer
